default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projectmng_development
  username: projectmng
  password: passwordais
  host: localhost
  port: 5432
  #min_messages: notice

test:
  <<: *default
  database: projectmng_test
  username: projectmng
  password: passwordais
  host: localhost
  port: 5432

production:
  <<: *default
  database: projectmng_production
  username: projectmng
  password: <%= ENV['PROJECTMNG_DATABASE_PASSWORD'] %>

  